services:
  - type: web
    name: floramart-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:app --workers 1 --worker-class uvicorn.workers.UvicornWorker
    region: oregon
